apiVersion: k3d.io/v1alpha3
kind: Simple
network: kube_vite_ma_planete
name: vite-ma-planete
servers: 1
agents: 3
options:
  k3s:
    extraArgs:
      - arg: --tls-san=https://cluster.vite-ma-planete.fr
        nodeFilters:
          - servers:*
      - arg: --disable=traefik
        nodeFilters:
          - servers:*
