---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secret
  namespace: default
spec:
  encryptedData:
    database-url: AgABEqLKYPv82elst2rxMLmB00Y2/rArFJzpexWv8EDola0H1HJA/ZUC44CFd5ms6P/RkHXQ/gxjxK+57Y5YRvp634wa3hY0lMzvsakynmgBLpS9VL+1B0LtzsUTKccy+C2YjtDBMvLVbuW8iuGCFajnMkVEFcp+K1hewvnnVryOQGenBb9G2LyNzjfRMCxKi450PXeNY7ZsCr9AJ3IzY+V7OGpisT7WkAl0GC4O0EOhpfihWzg+377ZMO/zzuS2+UEeqvXxNMd5iP7RR/thmCewx7JtHfXq13d4mc2f/54QYBVBg2Kx0HA4ovHDJP+RTCpuCdJpDeWwLoU7q8jrOsHX+5XxvBdb/sZqHQW2e1+8QwyVySpSZBZjPIlddTsfM+KdLtqgNb/i6xNfvWymiyTW4QV1KBvPuhOWfSes5UehyDdU0cuTGVO1PSvL65ITo3q8QwxC4WOuv9fiSGZwgJ/jcMXcphrHWSRCn7mWNWWlkmOk4Gi2IBKkmbZw1Y9yiOrsV9gpxvOKO/uF8bGVvuTx88glfYJIzhT616mFA/eskeEXKBXv2HzNVv86cjK42ztxNzgq8nbu/kifeqvWxgNy5z70u2SAjL5cyscHxhPIncJa1Qt9/Vn5b5oixzvYque6egn5cR6Fb3h9A/2P9dHu9q7CbNd/GVciIqtzDIKif2zhLlSJ7lNWf6RkjDnO6rGMfmYdr/504ZmQEeBP4GPLKFDIKnQlzXaECvQXgC99TH/eo2LgBFLbFGZjpprFv9ai6oWzgsky5VMejmydKZs1EyBYB0Gqc9Na5VBRMAPzaOWx6dZt7A==
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: default
    type: Opaque
