import './global.css';
import React from 'react';

export const metadata = {
  title: 'Welcome to www',
  description: 'Generated by create-nx-workspace',
};

export default function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  );
}
